# Generated by Django 5.2.3 on 2025-06-26 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Coffees', '0002_payments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='User',
        ),
        migrations.RemoveField(
            model_name='payments',
            name='User',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='coffee',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
        migrations.DeleteModel(
            name='OrderItems',
        ),
    ]
